### ISSUE TITLE
Give the ability to run tests for selected browser via command line args

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs-sphinx-search#9]
Currently, either the tests for both -- chrome and firefox -- will run or none will run.
We want to select the browser for tests.
Like:

```
pytest -v --chrome (runs the tests with chrome driver)
pytest -v --firefox (runs the tests with geckodriver)
pytest -v (runs the tests with both drivers)
```

**Comment by Jitesh-Dhoot** [comment]
if you are done on how to select browser from command line like this. please share

**Comment by dojutsu-user** [comment]
Hi @Jitesh-Dhoot 
I used [pytest-selenium](https://pytest-selenium.readthedocs.io/en/latest/index.html) for this.
You can read the docs here:
- https://pytest-selenium.readthedocs.io/en/latest/user_guide.html#specifying-a-browser
- https://readthedocs-sphinx-search.readthedocs.io/en/latest/testing.html#testing

**Comment by Jitesh-Dhoot** [comment]
can we do it without pytest-selenium package , using only pytest and selenium differently. I saw one post with conftest.py file pytest . but it did not work for me

**Comment by dojutsu-user** [comment]
I am not sure on this.
I think you can find some clue in the source code of pytest-selenium.
